CONSUMER_KEY        = "AAAAAAAAAAAAAAAAAAAAAAAAA"
CONSUMER_SECRET     = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
ACCESS_TOKEN        = "00000000-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
ACCESS_TOKEN_SECRET = "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"

SINCE               = '2023-01-31 23:50:00+09:00'
UNTIL               = '2023-02-01_01:10:00_JST'
HASH_TAG            = '#アルピーdcg'

OUTPUT_PATH         = '/Users/shg25/....'